apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: ks-docs-sample
    tier: backend
  name: ks-docs-sample
  namespace: kubesphere-docs-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: kubesphere
      component: ks-docs-sample
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubesphere
        component: ks-docs-sample
        tier: backend
    spec:
      containers:
      - env:
        - name: CACHE_IGNORE
          value: js|html
        - name: CACHE_PUBLIC_EXPIRATION
          value: 3d
        image: $DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME
        imagePullPolicy: Always
        name: ks-docs
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
